stages:
  prepare:
    cmd: python src/data/prepare.py
    deps:
      - data/raw/dataset.csv
      - src/data/prepare.py
    outs:
      - data/processed/data.pkl
  
  # train_single:
  #   cmd: python src/models/train_model.py
  #   deps:
  #     - data/processed/data.pkl
  #     - src/models/train_model.py
  #     - params.yaml
  #   outs:
  #     - models/default/default_run.pkl
  #   metrics:
  #     - metrics/default/default_run_metrics.json:
  #         cache: false
  #   params:
  #     - algorithm.hyperparameters.n_estimators
  #     - algorithm.hyperparameters.max_depth
  #     - algorithm.hyperparameters.min_samples_split
  #     - data.test_size
  #     - data.random_state
  
  run_experiments:
    cmd: python run_experiments.py
    deps:
      - data/processed/data.pkl
      - src/models/train_model.py
      - configs/all_experiments.yaml
    outs:
      - experiments_results.csv
      - experiments_summary.json
      - models/:
          cache: true
    metrics:
      - metrics/:
          cache: true